blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

blog/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
]

blog/article/models.py
from django.db import models

# Create your models here.

blog/article/views.py
from django.shortcuts import render



def article(request):
    '''
    Render the article page
    '''
    return render(request, 'article/article.html')

blog/main/views.py
from django.shortcuts import render
import random
import datetime

def main(request):
    '''
    Render the main page
    '''
    context = {'like':'Django 很棒 ' + str(random.randint(1,100))}
    context.update({'now':datetime.datetime.now()})
    return render(request, 'main/main.html', context)
def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>部落格說 -- Hello world!</h2> 
  </body>
</html>

blog/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>關於部落格</h2>
    <p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
  </body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>Django 說 -- Hello world!</h2>
    <p>{{ like }}</p>
    <p>目前時間:{{ now|date:'Y-m-d H:i' }}</p>
  </body>
</html>

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>